# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sergey Bedulin
email: serge.bedulin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Sergey Bedulin, Web Applications Developer from Irvine, CA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.bedulin.com" # the base hostname & protocol for your site
twitter_username:       serge_bedulin
github_username:        sbedulin
stackoverflow_username: sbedulin

# Build settings
markdown: kramdown
